sudo: required
services:
  - docker

script:
  - docker build -t mannyaboah/node .
  - docker images mannyaboah/node

before_deploy:
  - docker login -u mannyaboah -p Moose!23

deploy:
  provider: script
  script: docker push mannyaboah/node
  on:
    branch: master